# Use postgres/example user/password credentials
version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: billroo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
